#!/usr/bin/env php
<?php
// if you don't want to setup permissions the proper way, just uncomment the following PHP line
// read http://symfony.com/doc/current/book/installation.html#configuration-and-setup for more information
//umask(0000);

set_time_limit(0);

require_once __DIR__.'/../vendor/autoload.php';

use Symfony\Component\Console\Application;
use Onema\OpsWorksConsole\Command\CreateStackCommand;
use Onema\OpsWorksConsole\Command\UpdateStackChefCommand;
use Onema\OpsWorksConsole\Command\CreatePHPLayerCommand;
use Onema\OpsWorksConsole\Command\UpdatePHPLayerCommand;
use Onema\OpsWorksConsole\Command\CreateAppCommand;
use Onema\OpsWorksConsole\Command\UpdateAppCommand;
use Onema\OpsWorksConsole\Command\CreateStartInstanceCommand;
use Onema\OpsWorksConsole\Command\CreateAllCommand;

$application = new Application();
$application->add(new CreateStackCommand());
$application->add(new UpdateStackChefCommand());
$application->add(new CreatePHPLayerCommand());
$application->add(new UpdatePHPLayerCommand());
$application->add(new CreateAppCommand());
$application->add(new UpdateAppCommand());
$application->add(new CreateStartInstanceCommand);
$application->add(new CreateAllCommand());
$application->run();
       
